services:

  authentication:
    image: soumyasurpur/auth-service:latest
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: sqlite:////data/authentication.db
    volumes:
      - application_data:/data

  student:
    image: ananyaabhat/student-service:latest
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: sqlite:////data/students.db
    volumes:
      - student_data:/data

  internship:
    image: bhagyashree028/internship-service:v1
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: sqlite:////data/internships.db
    volumes:
      - internship_data:/data

  application:
    image: priya721k/application-service:v1
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: sqlite:////data/applications.db
    volumes:
      - application_data:/data

volumes:
  student_data:
  internship_data:
  application_data: